/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hr.algebra;

import com.formdev.flatlaf.FlatDarculaLaf;
import hr.algebra.admin.view.UploadMoviesPanel;
import hr.algebra.model.Movie;
import hr.algebra.model.MovieParser;
import hr.algebra.user.view.EditActorPanel;
import hr.algebra.user.view.EditDirectorPanel;
import hr.algebra.user.view.EditMoviesPanel;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.xml.stream.XMLStreamException;

/**
 *
 * @author zvonimir.ZI.ivancic
 */
public class MovieManager extends javax.swing.JFrame {
    
    private static final String UPLOAD_MOVIES = "Upload movies";
    private static final String EDIT_MOVIES = "Edit movies";
    private static final String EDIT_DIRECTOR = "Edit director";
    private static final String EDIT_ACTOR = "Edit actor";
    

    /**
     * Creates new form MovieManager
     */
    public MovieManager() {
        initComponents();
        configurePanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnParse = new javax.swing.JButton();
        tpContent = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnParse.setText("Parse");
        btnParse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpContent)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 1368, Short.MAX_VALUE)
                .addComponent(btnParse))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnParse))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnParseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParseActionPerformed
        try {
            List<Movie> movies = MovieParser.parse();
           // List<String> kifle = new ArrayList();
        } catch (IOException ex) {
            Logger.getLogger(MovieManager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (XMLStreamException ex) {
            Logger.getLogger(MovieManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnParseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
            try {
    UIManager.setLookAndFeel( new FlatDarculaLaf() );
} catch( Exception ex ) {
    System.err.println( "Failed to initialize LaF" );
}
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnParse;
    private javax.swing.JTabbedPane tpContent;
    // End of variables declaration//GEN-END:variables

    private void configurePanels() {
        
        tpContent.add(EDIT_MOVIES, new EditMoviesPanel());
        tpContent.add(EDIT_DIRECTOR, new EditDirectorPanel()); 
        tpContent.add(EDIT_ACTOR, new EditActorPanel()); 
        tpContent.add(UPLOAD_MOVIES, new UploadMoviesPanel()); 
    }
}
